// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCebt6DKd0mkkgZ1SgxGGelSxGiYXsOmy8',
    appId: '1:2857763010:android:85207888aa66e8bbebfb5b',
    messagingSenderId: '2857763010',
    projectId: 'biodata-form-b7067',
    storageBucket: 'biodata-form-b7067.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBswJYmpP3q4uulVpdRCKSm9VYkR4vq5Bs',
    appId: '1:2857763010:web:fbbe5ea2f91500dfebfb5b',
    messagingSenderId: '2857763010',
    projectId: 'biodata-form-b7067',
    authDomain: 'biodata-form-b7067.firebaseapp.com',
    storageBucket: 'biodata-form-b7067.firebasestorage.app',
    measurementId: 'G-1TQCS08WRB',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBswJYmpP3q4uulVpdRCKSm9VYkR4vq5Bs',
    appId: '1:2857763010:web:fbbe5ea2f91500dfebfb5b',
    messagingSenderId: '2857763010',
    projectId: 'biodata-form-b7067',
    authDomain: 'biodata-form-b7067.firebaseapp.com',
    storageBucket: 'biodata-form-b7067.firebasestorage.app',
    measurementId: 'G-1TQCS08WRB',
  );
}
